#!/usr/bin/perl
# Searching files in a directory
use warnings;
use strict;

# Author: Joseph Crisp
# Convert the Sequence FASTA File to a NEXUS File format and Create an accompanying TRAITS File

# Command Line Structure
# perl ConvertFasta2Nexus.pl combinedSampleInformation sequences.fasta sequenceNexus.txt traits.txt 

# Combined Smapling Info file structure:
# FileID	AgRID	Year	Host	Latitude	Longitude	Location	Area		REA	Source	Removed
# AgR288	NA		2011	BOVINE	-42.7324	171.15633	HOKITIKA	WESTCOAST	1	Farmed	0
# 0			1		2		3		4			5			6			7			8	9		10

# FASTA File Format:
#	110 2301				noSamples	noSites
#	>12754_8#26_114.vcf
#	ATGGAGGCCCCCAGCGCCGCTACTAGTGTTGCGGCAGACACCACGCCCCCCGCAGGACCCGGAGCCGGCCCGACCTACTTGGGGGGAATCCCTTGAGTCCTACCGGGGTAGCAAGTCACCGGACCCCCTTCTTGTGCCTGCTCTTTAACAGGGAAGCCTGTGTAGGCCGTCCGCGAGTTCCCCCTGCAGAGAACCCATCGCTCAGCTCCACACATCAGTGCTCGCCCCACCTGGCTGGTGACGACCCCTGACCCCGTGCGGTTTGACCCCAACTAACCGGTGCNGGGTTCGCGCTACTGAGGCCTCCGGACCCCGGGACTNNNCCACGGCGCACACCTCGCGACCGCCCCTAAGCACCGCTCCTACCCTACCCGTTGTCAAACACAACACTACGCCTAGCGGTGTGTCACGGATCCGGACCCCCCCACCGAGAAACCAACCTGNNTCCCTTCGACGGCCGCTTCCACCCTTTCGTGAGGGCCCCTTCAGCGGCTGCGTTACGATTCTCGCCCCGTGAATACTTCGCCCTCGAGCAGCTTANNNNATCTCCGTTCACCTCGTCTCGACTCGCGGCACCCGAACNCTNCCTCAGCCCCCCCCGTACTAACCTCCCCAGGGGGAACGCGTCCGAGCGCCACTCGTTCACTCTCGCCGACGTCCCGCTACCCCCTGCACATGTGGCGGTTAGCCNGGCGCGGTCCCACACACCTCTACCCGCGGTGCGCCTGTGGGCAANCCGGAGTAGGGTTCAGCCAGGGTATCTACAGCCGACCTTACATGATGCCTCGGATCCCAGCNTCGCCTGTTACGATAAGTTTTGGCTCAATCTGAAGAGCCACCGCCTCCTCGCCTGGCCACCTGGACCCCACCGCCTGGTTGCCGGGNAGGGCTCTGGGNCGGCCGACGTTGCACGGTCGCGGGCCGCGTGCCTCCCCGCGCTCCGAACAGCGTCGCGGCCGNNTCTGGGGGATNNGGTAGCACCGCCCCGACCGCCCAGCCGATCCGTCACCAAGTCGGAGCTGCAGCCCCCCGCCGGCGCGGGCCCTAAGCCGGCAGTGCTTTCTCCCTGGGGACTGTCCCACGCGGGAGGAGGCCTGTGCGCCATGCTTTCTGGACGTCGGCGACTCCCTCTCCCTCGGGGAGATCATCCAGGGCCAACCAGCCTTCGTCTCAAGCGCGGGCTTGCGTGGCCGACCTATGCTGGACCAGCCCCGACCACGGATACCAACCGGGCCGCCTGCTCCGCCGGGACTCCTCACGCGCTCACANCGTGTCTGCCGCGTAGGATGGAGGTCGACCGCACGCTGCCAAGCGGGGACCCGTAGTAAGGTCGACTGTACGGGGACCGGGACCCCTGCCCCTTGCCGCGAGAACGTTCGCCCCACCAGACCGTCGCCGAATCGGGCCGCCTGTATACCGCCACTATGGCAGTTCCCGAACGAGGCGTAGCAGATTTCCCTCAACGTTCTCTCCCCACGAGGTACTGATCCCCACGCGGTCGGAAGCCCCACGTAGGTGTAGCGCGCAAACCGCCCGCGTTGGCGAGACGGCCTGCCGCATCCGTCCAGCCCCCGAGCTGGTCACACTTCCTGGGAGCGTCCGAGCAGGTCCGCCCAGCTCCGGCCAGGGGCCGCGCGTCGGGTTAGTCACGGATTTGAGACAGCGGGGGAACCCGCGGTGACCCGAGTGGATCCCCCGCAGTGAAGGGCAGAGCTCATGTATGCGGCTGCGAGGGACCCGACCGCGAGCCTGGGGACAGGNGGCAGCGTCGGAGAGCCTCTGTCTCGCGGCGGGGGGATTGTTGCGCATGCCCAACNAGCCCGAGGGAAGGATCTCGTCCTGGATCGGGAGCCCCGCTCCCCAGAATTGACTATTTCTGAGGAGCGCCGACCCCGAGCCGGGACGGGTCAGGTCCCGCCAAGGCGGACCGATCCGACTCCGCGGGACGGGGGTGGGGACTTGCGGGAGTGAGGCGGANGCCGGCGGCTACGAGGTCGCGAGTGGCGCGGGGAACGAGTGGTTGCGGAGTGCTCACCCCGTCAGGGGCGGCGGAGGNGACGGGGCGCTTCCACCGTCCACCGTAGGCCGTGCCGATNNNNNNNNNNGATGCGTTTGGAGGAGGGTGGGCCTTTGCCGCNCCGGGCGGGCCGATCTCTTTGCCCCGTGNGCACGGGCGCGGGGCCCCCGGATGCGCAGCGGCTAGAGACCCCGCCTTTCCCTTTACTGCCCTACGCAGGTCGCGGCAAGGTGGAGATCGAACGTACCCTGCGGCTACTNCGGGCTCTGGGTGGGTGTGCTCCGGCAAGGCCGCGTGAGACGGACGAGTTCAGCTGTCGAAAAGGGCCGTGGCTAACCNGTGGTCGCGGCCGGGTATCGCGGTACGGCGGTATTGGCCTTGTGGAGATCGATGNCGGGCGGGCAATTCGACTNCAGCACGGCTTCAGGGTCATATCCAGGCCGCAAGCAACGTGCTCGCTCCGAGACGGCTTGGGGCGTACAGCGACCTTGAAGGGCGGGACGGAGCGCAACAGTATCTGAGCGATGCCCCGTCGAGGAGGGGAGGGGTGGCATACTCCCGCTGGGTCGGCCTGGGCATTTCCGACTTCTGCCCCGAAGCAGCCGTGCGGCTAGAATCGTGGCGCGAGCGTCCCGCGGAGGGCGCGGGCAACGGCACGACGCACGGGGGCCGACGGGGGCTAGCGCAGAAGGAGAGCGGGGGGNATAGCNNNNNNNCCGCGGGATGGATGGTGCAGGGGGGAGCGCGGGAGGTCGGGACGTAGCAACATCNGGAGCGGGGNGTATTCCATCTACTGCTGCGAGAGCATCGGGCAGGTGGGCCGCTCCGCCGCAGCGTGTCCCTCGCGCGACGGGCTGNNCACGTCCGNCNCGCTGGGNCGCNCNGNCNGCAGAGAGGTNCGNCATGNNNCCGAAGTCCGCGATAAAGACCCGTGATGCCTCTCGGATTGGCGGTCTGGGCGACCGCCATCGCTCNGAGATGTCAGGGATTCNTGCGAATGTGGCGTAGCATGAGCAGGGCCCGGCCTATGGTCACCGGTTANNNNAGCCCCACGGCGGGAGCTAAACCGGCGCACATCTTCACTCAATAGCGGTTACAGCGACGAGCGCGTGAGTATCATCGGGGTAGTTCTGGCCAACGATTGCTGGGCCGTCCAAGATGAATGTGGTTTATGAGGTGGCCGCTCGCAGATGTTCGGACTTACGCGCGGCCCCGCGGCGGTGGCNGCGGTTGAAGTGCTGGGCATGGGGCCCCCAGGCCTCGGGGGGGG
#	>12754_8#27_115.vcf
#	ATGGAGGCCTCCAGCGCCGCTACCAGCGTCGTAGCAAACGCCACGCCCTTCGCAGGACCCGGAGCAGGCCCGACCTACTGGGGGAGCACCCCTTGAGTCCTACCGGGGTAGCAAGTCACCNGGCCCCCTTCCTGTGGCCGCCCTTTGACAAGGGGGCCTGCATAGGCCGTCCGCGAGTTCCCCCTGCGGGGAACTCATCGCTCAGCCCCGCACAGTAGTGCCCGCCCCGCCCGGCTGGTGACGTCCCATAACCCCGTGCGGCTTGACCCCNACTAACCGGTGCCGNGTNCGCGCTACTGAGGCGTCCGGACCCCGGGACTGCGCCATGGCGCGCACCTCGCGGTCCCCCCCAAGCACCGCTCCTACCCTACCCNTTGTCAAACACAACACTACGCCTAGCGGTGTGTCACGGATCCGGATCCCCCCACCGAGAAACCAACCTGCCNCCCTTCGCCGGCCGCTGCCACCCTTCCGTGATAGCCCCCTCGGCGGCTGCGTTACCATTCTCGCCCCATGAATATTTCGCCCTTGAGCAGCTTAGCCCATCTTCGTTCGCCTCGTCCCGACTTGCGGCACCCGAACGCTNTCTCAGCCACCTCCGTACCGACCTCCCCATGGGGAACGCGTNNGAGCACCACTCGTTCATTCCCGCCGACGTCCCGCTAGCCCCCGCGCGTGTGACGGTTAGCCCGGCGCGGCCCCACACACCTCTACCCGCGGCGCGTCGGTGGGCAANCCGAAGTAGGATCTAGCCAGGGTACCTACAGCCGACATCACACGATGCCTTGGACCCCAGCNCCGCCTGTTACGATAAGTTCCGGCCCGGTCTGAAGGGCCACCGCTTCTTCGCCTGGCCACCCGCACCCCACCGCCTGGCTGCCGGGGAGGGCTCTGGGGCGGCCGACGCTGCACGGTCGCGGGCCGCGTGCCTCCCCACGCTCCCNACAGCGCCGCGGTCGGGTCTGGGGGATGCGGTAGCACCGCCTCGACCGCCCAGCCGATCCGNCATCAAGTCGGACCTGCAGCGTCTCGCCGGCGCGGGNCCNAAACCAACAATGCTTTCTCCCTGGGGACTGTCCCACGCGGGAGGAGGCGTGCGCGCTATGCTGCCTGGACGTCCGCGACTCCCTCCCGCCCGGGCAGATCATCCCGGGCCAACCAGCCTTCGTCTCAAGCGCGGGCGTCTGTGGCCGCCCCACGCTGGACCGGCCCCGACCACGTATACCAACCCGGCCGCCTGCTTCGTCCGGACCCCTCACGCGCTCACAGCGCGTCTGCCGCGCAGGATGGAGGTTGGCCGCACGCTGCCAAGCGGGGGCCCGCAGTAAGGTCGACTGTCCAGGGACCGGGACCACTACTACCTGTCGCGAGAACGTTCACCCCACGAGACCGTCCCCGACGCGGGCCCCCTTTACACCGCCACTATGACAACTCCCGGGCGAGGCGTAGCAACTTTCCCTCAACGTCCTGGCCCCGCGAAGTACTAATCCCCACTCGGGCGGAGGCTCGACGTAGATGGGGCCCGTAAAGCGCCCGGGTTGGCGAGACGACTTTCCGCATCCGCCCGGCCCCCGAGCTAGTCACACTTCCTGGGGACGTCCGAGCCAGTCCGCCCCGCTCCGGCCGGGGGCCGCGNNTCTGGTTGGTCACGGATTTGAGACAGCTGGGGAACCCACGGTGATCCGAGTGGATCCTCCGCAGTGGAGGGCGGAGCTCGTGTATGCGGNTGCGAGGGACCCGACCGCGAGCCTGGGGACAGGAGGCAGTGTCGGAGAGTCTCCGTCTCACGGCGGGGGGACTGTTGCGTGCGCTCAACGAGCCGAAGGGAAGGATTTCGTTCCCGATCGGGAACCCCACTCCCCAAAATTGACCATTCCTGAGGAGCGCCGACCCCGAGCCGGGGCGGGTCGGGTCCTGCAGAGGCGGACCGTTCCGAATCCGCGGGGGGGGGGCGGGGACTTGCGGGAGTGAGGCGGANGCCGGCGGCTACGAGGTCGCGAGGGGCATAGGGAACGAATGGTTTCGGAGTGCTAGCCCCGTCAAGGGCGCCGGAGGCGACGGGTCGATTCCGCCGTCCACCGTAGGCCGCGCCGATAGAAGCAGGGGCTGCGTTTGGAGGAGAGTGAGCCTTTGCCGCCCCGGGTGGGTCGATCTCTTCGCCCCGTGGGCACGGGGGCGGGATCCCCGGAAGTGAACCGGCTGGAGACCCCGCCTTTCTCTTTGCAGCCCTACGCAGGTCGCGGCGAGGTGGCGATCGAACGTACCCTGCGGCTGCTTCGGGCTCTGGGTGGGTGTGCCCTGGCAAGGCGACGCGAGCCGGGCGGGTTCCGCTGTCAAGAAGGGACATAGCTAACCAGGGGTCTCGGCTGGGTATCACGGTACGGCGGTGTTGACCTTGTGGAGATCGGTGGCGAGCGGACGATTCGACCATAGCACGGCTTCGGGGGCATACCCGGGCCGCAAGCCACGTGCTCGATCCGAGACGGCTTGGGGTGTACAACGACCTTGAAGGGCGGAACGGAGCACAACAGCATCTGAGCGATGCCCTGTCCGGGAGGGGAGGGGTGGCATACTTCCGCTGGGTCAGCCGGGGCATTTCCGACCGCTGCCTCGCAGAGGCCGCGCGGCTAGAGTCGTGGCGTGAACGCCCCGCAGAGGGCGCGGTCGACGGCGTGACGCACGGGGACCGACGGAGGCTAGCGCAGAAGGAGAGCGGGGGGTATAGCTAGGGCGCCGCGGGATGGATGGTGCAGGGGGGGGCGCGGAAGGTCGGTACGCAGCGACATNCNGAGTGGTGTGTATTACATCTACTGCCGCGAGGACAGCGGGCAGATGGGGCGTTCCACCGCGGGGTGCCCCCCGCGCGACGGGCTGNNCACGTNNGGNACGCTGGGGCNCCCGGTCCGCGGNGAGGTTCGGCGTGCNNCCGAAGTCTCCGATCTATATCAGGGACGCCTTTCGGCTTGAAGGCCTGGGCGACCACCATTGCTCAGAGATGTTAGGAACTCACACGGGTGTGGCGTAGCATGAGCAGGGCCCGACCTACGGTCACCGGCTACCGAGGCCCCACGGCGGGAGCCAAACCGGAGCACATCTTAACTCAATAGCGGTTACAGCGAAAAGCGTGGGAGTACTGTCGAGGTAGTTTTGGCCAACGGTTGCTGGACCGTCCAAAGAGACCGCGGCTNGTGGGGTGACCGCTCGCAAGTGTTCGGATTTACGCGCGGCCCCGCAACGGTGGCCGCGGTTGGAGTGCTGGGTGTGAGGCCCCCAGAACTCGGGCGGCG
#	>12754_8#28_116.vcf
#	GTGGAGGCCCCCAGCGCCGCTACTAGTATTGCGGCAGACACCACGCCCCCCGCAGGACCCGGAGCCGGCCCGACCTACTTGGGGGGAATCCCTTGAGTCCTCCCGGGGTAGCAAGTCACCGGACCCCCTTCTTGTGGCTGCTCTTTAACAGAGAAGCCTGCGTAGGCTGTCCGCGAGTTCCCCCTGCAGGGAACCCATCGCTCAGCTCCACACATCAGTGCTCGCCCCACCTGGCTGGTGACGACCCCTGACCCCGTGCGGTTTGACCCCAACTAACCGGTGCCGGGTTCGCGCTACTGAGGCCTCCGGACCCCGGGACTNNNCCACGGCGCACACTTTGCGACCGCCCCTAAGCACCGCTCCTACCCTACCCGTTGTCAAACACAACACTACGCCTAGCGGTGTGTCACGGATCCGGACCCCCCCACCGAGAAACCAACCTGNNNCCCTTCGACGGCCGCTTCCACCCTTTCGTGAGGGCCCCTTCAGCGGCTGCGTTACGATTCTCGCCCCGTGAATACTTCGCCCTCGAGCAGCTTANNNNATCTCCGTTCACCTCGTCTCGACTCGCGGCACCCGAACGCTGCCTCAGCCCCCCCCGTACTAACCTCCCCAGGGGGAACGCGTCCGAGCGCCACTCGTTCACTCTCGCCGACGTCCCGCTACCCCCTGCACATGTGGCGGTTAGCCCGGCGCGGTCCCACACACCTCTACCCGCGGTGCGCCTGTGGGCAAGCCGAAGTAGGGTTCAGCCAGGGTATCNNNNGCCGACCTTACATGATGCCTCGGATCCCAGCNTCGCCTGTTACGATAAGTTTTGGCTCGATCTGAAGAGCCACCGCCTCCTCGCCTGGCCACCTGGACCCCACCGCCTGGTTGCCGGGNAGGGCTCTGGGCCGGCCGACGTTGCACGGTCGCGGGCCGCGTACCTCCCCGCGCTCCGAACAGCGTCGCGGCAGGGTCTGGGGGATGCGGTAGCACCGCCCCGACCGCCCAGCCGATCCGNCACCAAGTCGGAGCTGCAGCCCCCCGCCGGCGCGGGCCCTAAGCCGACAGTGCTTTCTCCCTGGGGACTGTCCCACGCGGGAGGAGGCCTGTGCGCCATGCTTTCTGGACGTCGGCGACTCCCTCTCCCTCGGGGAGATCATNCAGGGCCAACCAGCCTTCGTCTCAAGCGCGGGCTTGCGTGGCCGACCTACGCTGGACCAGCCCCGACCACGTATACCAACCCGGCCGCCTGCTCCGCCGGGACTCCTCACGCGCTCACAGCGTGTCTGCCGCGTAGGATGGAGGTCGACCGCATGCTGCCAAGCGGGGACCCGTAGTAAGGTCGACTGTACGGGGACCGGGACCCCTGTCCCTTGCCGCGAGAACGTTCGCCCCACCAGACCGTCGCCGAATCGGGCCGCCTGTATACCGCCACTATGGCAGTTCCCGAACGAGGCGTAGCAAACTTCCCTCAACGTTCTCTCCCCACGAGGTACTGATCCCCACGCGGTCGGAAGCCCCACGNAGGTGTAGCGCGTAAACCGCCCGCGTTGGCGAGACGGCCTGCCGCATCCGTCCAGCCCCCGAGCTGGTCACACTTCCTGGGAGCGTCCGAGCCGGTCCGCCCAGCTCCGGCCAGGGGCCGCGCGTCGGGTTAGTCACGGATTTGAGNCAGCGGGGGAACCCGCGGTGACCCGAGTGGATCCCCCGCAGTGAAGGGCAGAGCTCATGTATGCGGNTGCGAGGGACCCGACCGCGAGCCTGGGGACAGGAGGCAGCGTCGGAGAGCCTCTGTCTCGCGGCGGGGGGATTGTTGCGCATGCCCAACGAGCCCGAGGGAAGGATCTCGTCCTGGATCGGGAGCCCCGCTCCCCAGAATTGACTATTTCTGAGGAGCGCCGACCCCGAGCCGGGACGGGTCAGGTCCCGCCAAGGCGGACCGATCCGACTCCGCGGGACGGGGGTGGGGACTTGCGGGAGTGAGGCGGATGTCGGCGGCTACGAGGTCGCGNGTGGCGTGGGGAACGAGTGGTTGCGGAGTGCTCACCCCGTCAGGGGCNGCGGAGGCGACGGGGCGCTTCCACCGTCCACCGTAGGCCGTGCCGATNNNNNNNNNNGATGCGTTTGGAGGAGGGTGGGCCTTTGCCGCNCCGGGCGGGCCGATCTCTTTGCCCCGTGNGCACGGGCGCGGGGCCCCCGGATGCGCAGCGGCTAGAGACCCCGCCTTTCCCTTTACTGCCCTACGCAGGTCGCGGCAAGGTGGAGATCGAACGTACCCTGCGGCTACTNCGGGCTCTGGGTGGGTGTGCTCCGGCAAGGCCGTGTGAGACGGACGAGTTCAGCTGTCGAAAAGGGACGTAGCTAACCNGTGGTCGCGGCCGGGTATCGCGGTACGGCGGTATTGGCCTTGTGGAGATCGATGGCGGGCAGGCAATTCGANTNCAGCACGGCTTTAGGGTCATATCCAGGCCGCAAGCAACGTGCTCGCTCCGAGACGGCTTGGGGCGGACAGCGACCTTGAAGGGCGGGACGGAGCGCAACAGTATCTGAGCGATGCCCCGTCGAGGAGGGGAGGGGTGGCATACTCNCGCTGGGTCGGCCTGGGCATTTCCGACTTCTGCCCCGAAGCAGCCGTGCGGCTAGAATCGTGGCGCGAGCGTCCCGCGGAGGGCGCGGGCAACGGCACGACGCATGGGGGCCGACGGGGGCTAGCGCAGAAGGAGAGCGGGGGGCATAGCNNNNNNNCCGCGNNNNACGNGGTGCAGGGGGGAGCGCGGGAGGTCGGGACGTAGCAACATCCNGAGCGGGGNGTATTCCATCTACTGCTGCGAGAGCATCGGGCAGGTGGGCCGCTCCGNCGCAGGGTGTCCCTCGCGCGACGGGCTGCCCACGTCNGNCACGCTGGGGCGCNCGGTCNGCAGAGAGGTTCGGCATGCACCCGAAGTCCGCGATATAGACCCGTGATGCCTCTCGGATTGGCGGTCTGGGCGACCGCCATCGCTCNGAGATGTCAGGGATTCNTGCGAATGTGGCGTAGCATGAGCAGGGCCCCGCCTATGGTCACCGGTTANNNNAGCCCCACGGCGGGAGCTAAACCGGCGCACATCTTCACTCAATAGCGGTTACAGCGACGAGCGCGTGAGTATCATCGGGGTAGTTCTGGCCAACGATTGCTGGGCCGTCCAAGATGAATGTGGTTTATGAGGTGGCCGCTCGCAGATGTTCGGACTTACGCGCGGCCCCGCGGCGGTGGCNGCGGTTGAAGTGCTGGGCATGGGGCCCCCAGGCCTCGGGGGGGG

# NEXUS File Format: (Note the Year is tacked onto the end of the Sequence Name)
#	#NEXUS
#
#
#	BEGIN DATA;
#	DIMENSIONS NTAX=3 NCHAR=20;
#	FORMAT MISSING=N GAP=- DATATYPE=DNA;
#	MATRIX
#	AgR111_1987       ATGCGATGCGTAGGAGTAGG
#	AgR121_1988       ATGCGATGCGTAGGNGTAGG
#	AgR122_1992       ATGCGATGCGNAGGAGTAGG
#	;
#	END;

# TRAITS File Format:
#	traits		Species		Latitude	Longitude	Location	Area				CATTLE			REA
#	AgR111_1987	POSSUM		-45.3453	165.0333	STATIONBF	MACKENZIECOUNTRY	NONBOVINE		1
#	AgR121_1988	BOVINE		-45.3453	165.0333	STATIONBF	MACKENZIECOUNTRY	BOVINE			23
#	AgR122_1992	FERRET		-45.3453	165.0333	STATIONH	MACKENZIECOUNTRY	NONBOVINE		9

####################################
# Read in the sampling information #
####################################

# Open the sample information file
my $infoFile = shift @ARGV;
open INFO, $infoFile or die "Couldn't open $infoFile:$!";

# Initialise a hashtable to store the sample information
my %sampleInfo = ();
my $info;
my $cattle;

# Initialise the necessary variables for parsing the file
my $line;
my @cols;

# FileID	AgRID	Year	Host	Latitude	Longitude	Location	Area		REA	Source	Removed
# 0			1		2		3		4			5			6			7			8	9		10

# Begin reading the file
while(<INFO>){
	$line = $_;
	chomp($line);
	
	# Skip the header line
	next if $line =~ /^FileID/;
	
	# Split the line into its columns
	@cols = split /\,/, $line;
	
	# Is the current isolate from a cow?
	$cattle = "WILDLIFE";
	if($cols[3] eq "BOVINE"){
		$cattle = "BOVINE";
	}
	
	# Get the necessary information from the sample information file
	$info = $cols[0] . "_" . $cols[2] . "\t" . $cols[3] . "\t" . $cols[4] . "\t" . $cols[5] . "\t" . $cols[6] . "\t" . $cols[7] . "\t" . $cattle . "\t" . $cols[8];
	
	# Store the isolate's information
	$sampleInfo{$cols[0]} = $info;
}
close(INFO);

###############################################
# Read the FASTA file and Print out Sequences #
###############################################

# Open in the Sample Fasta File
my $fastaFile = shift @ARGV; 
open FASTA, $fastaFile or die "Couldn't open $fastaFile:$!";

# Open the Output Files
my $nexusFile = shift @ARGV; # Takes Output File name from Command Line Input
open NEXUS, ">$nexusFile" or die "Couldn't open $nexusFile:$!"; # Assigns NEXUS File to Label and checks it can be Opened

my $traitsFile = shift @ARGV;
open TRAITS, ">$traitsFile" or die "Couldn't open $traitsFile:$!";

# Print Header into Traits file
print TRAITS "traits\tSpecies\tLatitude\tLongitude\tLocation\tArea\tCATTLE\tREA\n";

# Initialise variables to record the sequence length and number of isolates
my $sequenceLength;
my $noTaxa;

# Initialise variable to handle the isolate data
my $sequence;
my $sampleId;
my $outputId;

my $lineNo = 0;
while(<FASTA>){
	$lineNo++;
	$line = $_;
	chomp($line);

	# Get the number of taxa and sites from the first line
	if($lineNo == 1){
		@cols = split /\ /, $line;
		$noTaxa = $cols[0];
		$sequenceLength = $cols[1];
		
		# Print the  header out into the NEXUS File
		#	#NEXUS
		#
		#
		#	BEGIN DATA;
		#	DIMENSIONS NTAX=3 NCHAR=20;
		#	FORMAT MISSING=N GAP=- DATATYPE=DNA;
		#	MATRIX
		#	AgR111_1987       ATGCGATGCGTAGGAGTAGG
		print NEXUS "#NEXUS\n\n\nBEGIN DATA;\nDIMENSIONS NTAX=$noTaxa NCHAR=$sequenceLength;\nFORMAT MISSING=N GAP=- DATATYPE=DNA;\nMATRIX\n";
		next;
	}
	
	# Are we looking at a new isolate?
	if($line =~ /^>/){
		@cols = split /\_/, substr($line, 1);
		
		# Print out the Information for the previous isolate
		if($lineNo > 2){
			
			print NEXUS "$outputId\t$sequence\n";
			
			# Sample Info:
			#	SampleId	[ ] ug/ml	yr isolatd	HOST	LOCATION	AREA		BST	PVU	BCL	RESTTYPE	Comments
			# 	0			1			2			3		4			5			6	7	8	9			10
			
			# Traits File:
			#	traits	Species	Location	Area	CATTLE		
				
			print TRAITS "$info\n";
		}
		
		# Get the sampleId of the Current isolate
		$sampleId = $cols[0]; # AgR145_S24_9.vcf or N11_S8_1.vcf
		if($line =~ /^>12754/ || $line =~ /^>12755/){ # >12754_8#67_159.vcf
			$sampleId = $cols[0] . "_" . $cols[1];
		}
		
		# Get the sample's year
		$info = $sampleInfo{$sampleId};
				
		$outputId = (split /\t/, $info)[0];
		
		# Reset the sequence
		$sequence = "";
	}else{
	
		$sequence = $sequence . "" . $line;
	}
}
### Print the last sequence out to file
print NEXUS "$outputId\t$sequence\n";
print TRAITS "$info\n";

# Finish Printing Nexus File
print NEXUS ";\nEND;\n";

# Close Used Files
close(FASTA);
close(NEXUS);
close(TRAITS);